app:
  tenant:
    datasource:
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 5
      minimum-idle: 2

spring:
  application:
    name: Spring Boot Skeleton

  datasource:
    url: jdbc:postgresql://localhost:5432/catalog
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: Catalog-Pool
      maximum-pool-size: 5
      minimum-idle: 2

  sql:
    init:
      mode: never

  flyway:
    enabled: false
    locations: classpath:/db/migration/catalog

  jooq:
    sql-dialect: POSTGRES

  threads:
    virtual:
      enabled: true
