app:
  tenant:
    cache:
      ttl-seconds: 300

spring:
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=300s,maximumSize=1000,recordStats

logging:
  level:
    org.springframework: ERROR
    es.bdo.skeleton: ERROR
