spring:
  application:
    name: Spring Boot Skeleton

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: user
    password: password

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
