name: Application Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_application:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up GraalVM JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'graalvm'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Compile Application (Assemble)
        run: ./gradlew assemble

      - name: Upload Compiled Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-app-files
          path: build/
