name: Application Build

on:
  push:
    branches: [ main ]

jobs:
  build_application:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up GraalVM JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'graalvm'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Docker Image (Native)
        run: ./gradlew bootBuildImage -PnativeImage=true

      - name: Save Docker Image to File
        run: |
          docker save es.bdo/skeleton:0.0.1 | gzip > skeleton-native.tar.gz

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-native
          path: skeleton-native.tar.gz
          retention-days: 7

      - name: Upload Compiled Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-app-files
          path: build/native/nativeCompile/
